version: "3"
services:
  metadata:
    build:
      context: .
      dockerfile: Dockerfile
    image: jns-metadata-service
    ports:
      - "8080:8080"
    environment:
      - ADDRESS_ETH_REGISTRAR=0x4Dd6dc791F79bc85766649FC3e42059c564703BD
      - ADDRESS_NAME_WRAPPER=0xc57de38dBcB35473773f84A553F2Ab5fC23B4653
      - RPC_PROVIDER=https://rpc.testnet.jfinchain.com
      - SUBGRAPH_URL=http://graph-node:8000/subgraphs/name/graphprotocol/ens
